# Generated by Django 2.1.15 on 2020-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=1000)),
                ('event', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
