# Generated by Django 2.2.15 on 2020-08-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20200828_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.ManyToManyField(null=True, related_name='event_product', to='promotions.Product'),
        ),
    ]
