# Generated by Django 2.1.15 on 2020-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=200)),
                ('atm', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('wine', models.CharField(max_length=200)),
                ('lotto', models.CharField(max_length=200)),
                ('bakery', models.CharField(max_length=200)),
                ('delivery', models.CharField(max_length=200)),
            ],
        ),
    ]
